server:
  port: 8050

spring:
  application:
    name: inner-gateway-service
  cloud:
    gateway:
      # 开启基于服务发现的路由规则
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    # 使用IP注册
    preferIpAddress: true
    # Client向Eureka Server发送心跳的时间间隔，默认30s (线上可适当提高该值来防止触发自我保护)
    lease-renewal-interval-in-seconds: 30
    # 服务失效剔除时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    # 用于在重新启动后触发信息和端点更新
    metadata-map:
      startup: ${random.int}
  client:
    # 是否将该当前实例注册到Eureka Server
    register-with-eureka: false
    # 是否获取注册表信息
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@localhost:9001/eureka/,http://admin:123456@localhost:9002/eureka/
    # 拉取注册信息间隔。默认30秒 (测试环境，可适当降低该值来保证及时获取注信息)
    registry-fetch-interval-seconds: 5

logging:
  level:
    # SpringCloud网关日志配置
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG