FROM java:alpine
LABEL maintainer="waynechu@waynechu.cn"
LABEL version="1.0.0"
LABEL description="Base skywalking image for SpringCloud application."
ADD /apache-skywalking-apm-bin/agent/ /opt/skywalking-agent/