version: '3'
services:
  mysql-master:
    image: mysql:8.0.12   #镜像
    container_name: biz-mysql-master   #容器名
    restart: always    #重启容器策略: 1.null 默认策略,退出后不重启  2.on-failure 非正常退出会重启,on-failure:3还能指定尝试重启次数  3.always 容器退出时总是重启  4.unless-stopped 在容器退出时总是重启容器,但是不考虑在Docker守护进程启动时就已经停止了的容器
    networks:   #配置容器连接的网络,引用顶级networks下的条目
      biz-net:
        ipv4_address: 172.20.0.2
    ports:
      - 3306:3306   #宿主机与容器的端口映射规则
    volumes:   #数据卷或者文件挂载到容器
      - ./data/mysql/master/mysql:/var/lib/mysql
      - ./data/mysql/master/mysql-files:/var/lib/mysql-files
      - ./config/mysql/mysql-master.cnf:/etc/mysql/my.cnf
      - ../sql:/docker-entrypoint-initdb.d/   #MySQL第一次启动时执行会执行该路径下的SQL脚本
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456

  mysql-slave1:
    image: mysql:8.0.12
    container_name: biz-mysql-slave1
    restart: always
    networks:
      biz-net:
        ipv4_address: 172.20.0.3
    ports:
      - 3307:3306
    depends_on:
      - mysql-master
    volumes:
      - ./data/mysql/slave1/mysql:/var/lib/mysql
      - ./data/mysql/slave1/mysql-files:/var/lib/mysql-files
      - ./config/mysql/mysql-slave1.cnf:/etc/mysql/my.cnf
      - ../sql:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456

  mysql-slave2:
    image: mysql:8.0.12
    container_name: biz-mysql-slave2
    restart: always
    networks:
      biz-net:
        ipv4_address: 172.20.0.4
    ports:
      - 3308:3306
    depends_on:
      - mysql-master
    volumes:
      - ./data/mysql/slave2/mysql:/var/lib/mysql
      - ./data/mysql/slave2/mysql-files:/var/lib/mysql-files
      - ./config/mysql/mysql-slave2.cnf:/etc/mysql/my.cnf
      - ../sql:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis:latest
    container_name: biz-redis
    restart: always
    command: redis-server --requirepass 123456
    volumes:
      - ./data/redis:/data
    networks:
      biz-net:
        ipv4_address: 172.20.0.5
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: biz-rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      biz-net:
        ipv4_address: 172.20.0.6
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env   #从文件添加环境变量

networks:
  biz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16