version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: biz-mysql
    restart: always
    networks:
      biz-net:
        ipv4_address: 172.20.0.2
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis:latest   #镜像
    container_name: biz-redis   #容器名
    restart: always   #重启容器策略: 1.no 默认策略,退出后不重启  2.on-failure 非正常退出会重启,on-failure:3还能指定尝试重启次数  3.always 容器退出时总是重启  4.unless-stopped 在容器退出时总是重启容器,但是不考虑在Docker守护进程启动时就已经停止了的容器
    command: redis-server --requirepass 123456
    volumes:   #数据卷或着文件挂载到容器
      - ./data/redis:/data
    networks:   #配置容器连接的网络,引用顶级networks下的条目
      biz-net:
        ipv4_address: 172.20.0.5
    ports:   #宿主机与容器的端口映射规则
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: biz-rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      biz-net:
        ipv4_address: 172.20.0.6
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env   #从文件添加环境变量

  elasticsearch:
    image: elasticsearch:7.5.1
    container_name: biz-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:   #覆盖容器默认的 ulimit
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      biz-net:
        ipv4_address: 172.20.0.7
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.5.1
    container_name: biz-kibana
    restart: always
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      biz-net:
        ipv4_address: 172.20.0.8
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.5.1
    container_name: biz-logstash
    restart: always
    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      biz-net:
        ipv4_address: 172.20.0.9
    ports:
      - 7002:7002
    depends_on:
      - elasticsearch
      - kibana

networks:
  biz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16