version: '3'
services:
  redis: 
    image: redis:latest   #镜像
    container_name: biz-redis   #容器名
    restart: always   #重启容器策略: 1.no 默认策略,退出后不重启  2.on-failure 非正常退出会重启,on-failure:3还能指定尝试重启次数  3.always 容器退出时总是重启  4.unless-stopped 在容器退出时总是重启容器,但是不考虑在Docker守护进程启动时就已经停止了的容器
    command: redis-server --requirepass 123456
    volumes:   #数据卷或着文件挂载到容器
      - ./data/redis:/data
    networks:   #配置容器连接的网络,引用顶级networks下的条目
      biz-net:
        ipv4_address: 172.20.0.2
    ports:   #宿主机与容器的端口映射规则
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: biz-rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      biz-net:
        ipv4_address: 172.20.0.3
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env   #从文件添加环境变量

  mysql:
    image: mysql:5.7
    container_name: biz-mysql
    restart: always
    networks:
      biz-net:
        ipv4_address: 172.20.0.4
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456

networks:
  biz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16