version: '3'
services:
  eureka-1:
    image: biz-spring-cloud-eureka:1.0.2019070901-RELEASE
    container_name: biz-spring-cloud-eureka-1
    networks:
      biz-net:
        ipv4_address: 172.20.0.12
    ports:
      - 9001:8080
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prd -Denv=DEV -Dapollo.configService=http://172.20.0.10:8080 -Ddev_meta=http://172.20.0.10:8080 -server -Xms256m -Xmx256m -Xmn100m -Xss256k -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=80 -XX:+UseCMSInitiatingOccupancyOnly -XX:AutoBoxCacheMax=20000 -XX:-OmitStackTraceInFastThrow -Djava.rmi.server.hostname=local_ip -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=12345
      - server.port=9001
      - eureka.client.service-url.defaultZone=http://${spring.security.user.name}:${spring.security.user.password}@172.20.0.12:9001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@172.20.0.13:9002/eureka/

  eureka-2:
    image: biz-spring-cloud-eureka:1.0.2019070901-RELEASE
    container_name: biz-spring-cloud-eureka-2
    networks:
      biz-net:
        ipv4_address: 172.20.0.13
    ports:
      - 9002:8080
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prd -Denv=DEV -Dapollo.configService=http://172.20.0.10:8080 -Ddev_meta=http://172.20.0.10:8080 -server -Xms256m -Xmx256m -Xmn100m -Xss256k -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=80 -XX:+UseCMSInitiatingOccupancyOnly -XX:AutoBoxCacheMax=20000 -XX:-OmitStackTraceInFastThrow -Djava.rmi.server.hostname=local_ip -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=12345
      - server.port=9001
      - eureka.client.service-url.defaultZone=http://${spring.security.user.name}:${spring.security.user.password}@172.20.0.12:9001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@172.20.0.13:9002/eureka/

networks:
  biz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

