server:
  port: 8060

spring:
  application:
    name: boot-admin-service

eureka:
  client:
    # 是否将该当前实例注册到Eureka Server
    register-with-eureka: false
    # 是否获取注册表信息
    fetch-registry: true
    service-url:
      defaultZone: http://admin:EOus8'aw$q+P@localhost:9001/eureka/,http://admin:EOus8'aw$q+P@localhost:9002/eureka/
    # 拉取注册信息间隔。默认30秒 (测试环境，可适当降低该值来保证及时获取注信息)
    registry-fetch-interval-seconds: 30