server:
  port: 8020

spring:
  application:
    name: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:9001/eureka/,http://admin:123456@localhost:9002/eureka/

feign:
  # feign压缩配置
  compression:
    request:
      # 配置Feign请求开启GZIP压缩。默认false
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限。默认2048
      min-request-size: 2048
    response:
      # 配置Feign响应开启GZIP压缩。默认false
      enabled: true
  client:
    config:
      github-client: # 特定FeignClient的配置
        loggerLevel: full # 日志级别
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000 # 读超时时间
        #retryer: 重试配置
        #errorDecoder:
        #requestInterceptors:
        #decode404:
        #decoder:
        #encoder:
        #contract:

logging:
  level:
    # 查看feign详细调用日志
    cn.waynechu.springcloud.feign.remote.GitHubRemote: debug
    cn.waynechu.springcloud.feign.remote.UserRemote: debug
